name: Client Build Check

on:
  pull_request:
    branches: [ master, develop ]
env:
  ANGUALR_DIR: src/client
  NODE_VERSION: 12.x
jobs:
  Build_Angular_withTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    build:
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{env.ANGUALR_DIR}}
    - name: Clean Install
      run: npm ci
      working-directory: ${{env.ANGUALR_DIR}}
    - name:Run Build
      run: npm run build --if-present
      working-directory: ${{env.ANGUALR_DIR}}
    - name: Run Tests
      run: npm test
      working-directory: ${{env.ANGUALR_DIR}}
