name: Deploy Server to Azure

on:
  push:
    branches: [ master ]
env:
  SERVER_DIR: src/server/MUDhub.Server
  SOLUTION_DIR: src/server
  DOTNET_SDK_VERSION: 3.1.101 
  WORKDIR_DEST: dest
jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_SDK_VERSION}}
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.SERVER_DIR}}
    - name: Build Server
      run: dotnet build *.csproj --configuration Release --no-restore -o ${{env.WORKDIR_DEST}}
      working-directory: ${{env.SERVER_DIR}}
      
#    - name: Setup Node.js 12
#      uses: actions/setup-node@v1
#      with:
#        node-version: 12.x
#    - name: Install Angular
#      run: npm ci
#      working-directory: ${{env.WORKDIR_CLIENT}}      
#    - name: Build Angular Client
#      run: npm run build -- --prod
#      working-directory: ${{env.WORKDIR_CLIENT}}    
#    - name: Copy dist Files
#      run: cp -r ${{env.WORKDIR_CLIENT}}/dist ${{env.WORKDIR_DEST}}
    
    - name: Publish to Azure Web services
      uses: azure/webapps-deploy@v1
      with:
        app-name: MUDhub
        publish-profile: ${{  secrets.AZURE_DELOYMENT_KEY }} 
        package: ${{env.WORKDIR_DEST}}
